"""Draws the pipeline architecture diagram with matplotlib (no graphviz/system dependency --
the `dot` binary isn't available in this environment). Writes reports/architecture.png."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "reports" / "architecture.png"

STAGE_COLOR = "#cfe3f7"
EXPERIMENT_COLOR = "#e8f5d0"
SERVING_COLOR = "#fde3c8"
ARTIFACT_COLOR = "#eeeeee"

fig, ax = plt.subplots(figsize=(15, 8))
ax.set_xlim(0, 15)
ax.set_ylim(0, 8)
ax.axis("off")


def box(x, y, w, h, text, color, fontsize=9):
    ax.add_patch(mpatches.FancyBboxPatch(
        (x, y), w, h, boxstyle="round,pad=0.08", linewidth=1, edgecolor="#333333", facecolor=color,
    ))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fontsize, wrap=True)


def arrow(x1, y1, x2, y2):
    ax.annotate(
        "", xy=(x2, y2), xytext=(x1, y1),
        arrowprops={"arrowstyle": "->", "color": "#333333", "lw": 1.4},
    )


# --- Main pipeline, left to right ---
stage_y = 5.6
stage_w, stage_h = 2.1, 1.3
stage_x = [0.3, 2.7, 5.1, 7.5, 9.9, 12.3]
stage_labels = [
    "Dataset\ncharacterization\n(characterize.py,\nquality.py)",
    "Augmentation\nstrategy\n(augmentation.py)",
    "Localization\n(MegaDetector,\ndetector.py)",
    "Classifier\ntraining\n(training_run.py)",
    "Evaluation\n(classifier_metrics.py,\ndetector_metrics.py)",
    "Serving\n(FastAPI,\napp.py)",
]
for x, label in zip(stage_x, stage_labels):
    box(x, stage_y, stage_w, stage_h, label, STAGE_COLOR)
for i in range(len(stage_x) - 1):
    arrow(stage_x[i] + stage_w, stage_y + stage_h / 2, stage_x[i + 1], stage_y + stage_h / 2)

# --- Secondary experiments, branching off classifier training ---
exp_y = 3.6
exp_w, exp_h = 2.1, 1.0
exp_labels = [
    "Site-holdout split\n(generalization check)",
    "Multi-seed\ncomparison",
    "Hyperparameter\nsearch",
]
for i, label in enumerate(exp_labels):
    x = 5.1 + i * 2.4
    box(x, exp_y, exp_w, exp_h, label, EXPERIMENT_COLOR, fontsize=8)
    arrow(7.5 + stage_w / 2, stage_y, x + exp_w / 2, exp_y + exp_h)

# --- MLflow / registry, under training+evaluation ---
mlflow_x, mlflow_y, mlflow_w, mlflow_h = 7.5, 1.6, 4.5, 1.0
box(mlflow_x, mlflow_y, mlflow_w, mlflow_h, "MLflow (SQLite) + Model Registry\n(promote_classifier.py: explicit \"production\" alias)", ARTIFACT_COLOR, fontsize=8)
arrow(8.55, stage_y, mlflow_x + 1.0, mlflow_y + mlflow_h)
arrow(mlflow_x + mlflow_w - 1.0, mlflow_y + mlflow_h, 12.3 + stage_w / 2, stage_y)

# --- Reports, under everything ---
reports_x, reports_y, reports_w, reports_h = 0.3, 0.2, 6.6, 1.0
box(reports_x, reports_y, reports_w, reports_h, "reports/*.md, *.png, *.csv\n(regenerated by scripts/generate_*.py, evaluate_*.py)", ARTIFACT_COLOR, fontsize=8)
arrow(1.35, stage_y, reports_x + 1.5, reports_y + reports_h)
arrow(6.15, stage_y, reports_x + reports_w - 1.5, reports_y + reports_h)

# --- Serving outputs ---
api_x, api_y, api_w, api_h = 12.0, 3.6, 2.6, 1.0
box(api_x, api_y, api_w, api_h, "POST /predict\nPOST /predict/batch\nGET /health, /metrics", SERVING_COLOR, fontsize=8)
arrow(13.35, stage_y, 13.35, api_y + api_h)

ax.set_title("Camera Trap Species Classifier -- Pipeline Architecture", fontsize=13, pad=15)

fig.savefig(OUTPUT_PATH, dpi=150, bbox_inches="tight")
print(f"Wrote {OUTPUT_PATH}")
