"""Trains the same backbones as scripts/train_classifier.py but on a site-disjoint split: every
crop from a given camera site lands entirely in one of train/val/test, so the resulting test
accuracy measures generalization to camera sites the model never saw during training, not just to
unseen images from already-seen sites. See reports/site_holdout_evaluation.md for the numbers,
generated by scripts/evaluate_classifier_site_holdout.py."""
import os
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

os.environ.setdefault("MLFLOW_ALLOW_FILE_STORE", "true")

import mlflow
import numpy as np
import torch

from src.classifier.data_prep import build_labeled_crop_df
from src.classifier.split import group_images_by_site, split_groups
from src.classifier.training_run import train_and_compare_backbones
from src.evaluation.segmentation import build_site_lookup
from src.utils.config import load_config

ROOT = Path(__file__).resolve().parents[1]
DETECTIONS_PATH = ROOT / "data" / "localization" / "detections.json"
CROPS_DIR = ROOT / "data" / "localization" / "crops"
ANNOTATIONS_PATH = ROOT / "data" / "raw" / "caltech_images_20210113.json"
BBOX_PATH = ROOT / "data" / "raw" / "caltech_bboxes_20200316.json"
CONFIG_PATH = ROOT / "configs" / "train_classifier_site_holdout.yaml"
CHECKPOINT_DIR = ROOT / "data" / "checkpoints_site_holdout"

config = load_config(CONFIG_PATH)
SEED = config["seed"]
EPOCHS = config["epochs"]
BATCH_SIZE = config["batch_size"]
LEARNING_RATE = config["learning_rate"]
MIN_SAMPLES_PER_SPECIES = config["min_samples_per_species"]
EARLY_STOPPING_PATIENCE = config["early_stopping_patience"]
BACKBONES = tuple(config["backbones"])

if EPOCHS < 1:
    raise SystemExit(f"configs/train_classifier_site_holdout.yaml: epochs must be >= 1, got {EPOCHS}")

for path in (DETECTIONS_PATH, ANNOTATIONS_PATH, BBOX_PATH):
    if not path.exists():
        raise SystemExit(f"{path} not found -- run the localization and download scripts first.")

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

crop_df, images_df = build_labeled_crop_df(DETECTIONS_PATH, ANNOTATIONS_PATH, BBOX_PATH, MIN_SAMPLES_PER_SPECIES)
print(f"{len(crop_df)} labeled crops across {crop_df['species'].nunique()} species")

# --- Site-disjoint split: group by camera site instead of near-duplicate image ---
site_lookup = build_site_lookup(images_df)
groups = group_images_by_site(crop_df["source_image"].unique().tolist(), site_lookup)
crop_df["group_id"] = crop_df["source_image"].map(groups)
crop_df["split"] = split_groups(crop_df, seed=SEED)

train_df = crop_df[crop_df["split"] == "train"].reset_index(drop=True)

# A species confined to camera sites that all land outside train has no way to appear in more than
# one split -- drop it everywhere rather than scoring a class the model never saw, same guard
# train_classifier.py uses for its near-duplicate split.
train_species = set(train_df["species"].unique())
species_without_train_examples = set(crop_df["species"].unique()) - train_species
if species_without_train_examples:
    print(
        f"Dropping {len(species_without_train_examples)} species with zero train examples "
        f"(confined to non-train sites): {sorted(species_without_train_examples)}"
    )
    crop_df = crop_df[crop_df["species"].isin(train_species)].reset_index(drop=True)
    train_df = crop_df[crop_df["split"] == "train"].reset_index(drop=True)

val_df = crop_df[crop_df["split"] == "val"].reset_index(drop=True)
test_df = crop_df[crop_df["split"] == "test"].reset_index(drop=True)
print(f"train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")
print(
    f"sites: train={train_df['source_image'].map(groups).nunique()}, "
    f"val={val_df['source_image'].map(groups).nunique()}, "
    f"test={test_df['source_image'].map(groups).nunique()}"
)

if train_df.empty or val_df.empty:
    raise SystemExit("Train or val split is empty -- not enough sites to proceed.")

species_to_index = {s: i for i, s in enumerate(sorted(crop_df["species"].unique()))}

mlflow.set_tracking_uri((ROOT / "mlruns").as_uri())
mlflow.set_experiment("camera-trap-classifier-site-holdout")

results = train_and_compare_backbones(
    train_df, val_df, CROPS_DIR, species_to_index, BACKBONES, SEED, EPOCHS, BATCH_SIZE,
    LEARNING_RATE, EARLY_STOPPING_PATIENCE, device, CHECKPOINT_DIR,
    mlflow_params={"split_strategy": "site_holdout"}, artifact_paths=[CONFIG_PATH],
)

print("\nComparison (final val accuracy, site-disjoint split):")
for backbone, metrics in results.items():
    print(f"  {backbone}: {metrics['accuracy']:.3f}")
